backend:
  name: git-gateway
  branch: master 

media_folder: "public/images/uploads"
public_folder: "/images/uploads"       

collections:
  - name: "blog"
    label: "Blogi"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/BlogPost.astro"}
      - {label: "Otsikko", name: "title", widget: "string"}
      - {label: "Julkaisupäivä", name: "pubDate", widget: "datetime"}
      - {label: "Kuvaus", name: "description", widget: "text"}
      - {label: "Kansikuva", name: "heroImage", widget: "image", required: false}
      - {label: "Leipäteksti", name: "body", widget: "markdown"}